### ISSUE TITLE
image build from github does not work with docker  1.13.0

### ISSUE THREAD

**Issue by joeribelis** [pdubois/docker-alfresco#5]
When i build the image from github

and run it with 

docker run -d --name "alfresco" mybuild/alfresco

it stops after 22 sec. this is the output of sudo systemctl status docker

Jan 31 08:45:55 minastirith dockerd[980]: time="2017-01-31T08:45:55.802082328+01:00" level=warning msg="Your kernel does not support swap memory limit."
Jan 31 08:45:55 minastirith dockerd[980]: time="2017-01-31T08:45:55.802537308+01:00" level=warning msg="Your kernel does not support cgroup rt period"
Jan 31 08:45:55 minastirith dockerd[980]: time="2017-01-31T08:45:55.802772346+01:00" level=warning msg="Your kernel does not support cgroup rt runtime"
Jan 31 08:46:17 minastirith dockerd[980]: time="2017-01-31T08:46:17.511982033+01:00" level=error msg="containerd: deleting container" error="exit status 1: \"container 48fa44f04b8942656e3c078c0fdb6e53101e8bdda7d21b3ba191d
lines 1-22/22 (END)

output from docker logs <container>

About to clean out /opt/alfresco/tomcat/webapps/alfresco and share directories and temporary files...
Press control-c to stop this script . . .
Press any other key to continue . . .
Cleaning temporary Alfresco files from Tomcat...
Traceback (most recent call last):
  File "/passencode.py", line 6, in <module>
    encrypted = hashlib.new('md4', passwd.encode('utf-16le')).hexdigest()
AttributeError: 'NoneType' object has no attribute 'encode'

and docker version

Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false

Any idea why this build is not possible?

**Comment by joeribelis** [comment]
I have found i need the -e INITIAL_PASS parameter. Maybe i missed it in the documentation.
